on: [push, pull_request]
name: build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Time
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: Hello-World! Today is-${{ steps.date.outputs.date }}
